# Generated by Django 4.1.7 on 2024-04-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='city_name',
            field=models.CharField(default='BG', max_length=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='street',
            field=models.CharField(choices=[('s1', 's1'), ('s2', 's2'), ('s3', 's3'), ('s4', 's4')], max_length=8),
        ),
    ]
